// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTgXawSpX5EIaxITIJP1vBpSbgRJSOqM',
    appId: '1:996778997219:web:25e8af2e698142c962dcd6',
    messagingSenderId: '996778997219',
    projectId: 'flutter-shop-app-780d7',
    authDomain: 'flutter-shop-app-780d7.firebaseapp.com',
    storageBucket: 'flutter-shop-app-780d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNcrS0eqi7paCkRTU9RIswTiG8-jRzSQ',
    appId: '1:996778997219:android:15a8b412b56123fa62dcd6',
    messagingSenderId: '996778997219',
    projectId: 'flutter-shop-app-780d7',
    storageBucket: 'flutter-shop-app-780d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt73zGkLIJfJGIhvY5bOXBBQmFrrJjOTw',
    appId: '1:996778997219:ios:570a902020d4666e62dcd6',
    messagingSenderId: '996778997219',
    projectId: 'flutter-shop-app-780d7',
    storageBucket: 'flutter-shop-app-780d7.appspot.com',
    iosClientId: '996778997219-qaqcvfl0vq5b8nrgn3q6hji1bqf5trvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt73zGkLIJfJGIhvY5bOXBBQmFrrJjOTw',
    appId: '1:996778997219:ios:570a902020d4666e62dcd6',
    messagingSenderId: '996778997219',
    projectId: 'flutter-shop-app-780d7',
    storageBucket: 'flutter-shop-app-780d7.appspot.com',
    iosClientId: '996778997219-qaqcvfl0vq5b8nrgn3q6hji1bqf5trvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
